config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'

  authenticate :user, ->(u) { u.is_admin? || u.is_employee? } do
    # These are things users shouldn't even know exist if they aren't an admin
    resources :interventions
    resources :addresses, only: %i[index]
    get 'interventions', to: 'interventions#interventions'
    get 'buildings', to: 'interventions#buildings'
    get 'batteries', to: 'interventions#batteries'
    get 'columns', to: 'interventions#columns'
    get 'elevators', to: 'interventions#elevators'
    get 'speech', to: 'azure_speech#index'
    get 'speech/transcribe', to: 'azure_speech#speech_transcription'
    get 'verify_audio', to: 'azure_speech#verify_audio'
    post 'upload_audio', to: 'azure_speech#upload_audio'
    get 'create_profile_id', to: 'azure_speech#create_profile_id'
    get 'enroll_profile', to: 'azure_speech#enroll_new_profile'
  end

  resources :leads

  resources :quotes, only: %i[user_quotes new create]

  root to: 'static_pages#index'
  get 'static_pages/residential'
  get 'static_pages/corporate'

  devise_for :users,
             controllers: {
               registrations: 'users/registrations', sessions: 'users/sessions'
             },
             path_names: {
               sign_in: 'sign_in',
               sign_out: 'sign_out',
               password: 's',
               confirmation: 'v'
             }

  get 'my_quotes' => 'quotes#user_quotes', as: :my_quotes
  get 'my_leads' => 'leads#user_leads', as: :my_leads

  resource :messages do
    collection { post 'reply' }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rocket Elevators</title>
    <script>
      var plugin_path = 'vendor/assets/javascripts/'
    </script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:head_tags) %>
    <%= include_recaptcha_js %>
  </head>
  <body class="smoothscroll enable-animation">
    <div id="page-container">
      <%= render 'partials/header' %>
      <div id="wrapper">
        <%= render 'partials/alerts'%>
        <%= yield %>
        <% if !current_page?(addresses_path) %>
          <%= render 'partials/footer' %>
        <% end %>
      </div>
    </div>
    <!-- SCROLL TO TOP -->
    <a href="#" id="toTop"></a>
    <!-- PRELOADER -->
    <div id="preloader">
      <div class="inner">
        <span class="loader"></span>
      </div>
    </div>
    <!-- /PRELOADER -->
    <%= javascript_include_tag 'scripts' %>
  </body>
</html>